### ISSUE TITLE
!bg<n>

### ISSUE THREAD

**Issue by Heanthor** [Heanthor/auctioneer-bot#16]
Let the user specify how many of an item they are trying to craft. We calculate the amount of materials they will need, and then use absolute auctions to give them the real lowest price, not an average.

Note: this is handicapped heavily by delayed AH data.

**Comment by Heanthor** [comment]
@unlockedSound is this even feasible with the big delay?

**Comment by unlockedSound** [comment]
Yes... will a bit of smart meth

**Comment by unlockedSound** [comment]
a few things we can do:
-buffer the amount needed slightly (like 20% rounded up or something) to buffer the amount that makes sense
-list the max buyouts before it is no longer viable
-get really interesting and look for the break points in buyout pricing so we can define 'price sets'; this would allow us to really tell a user a price point for different products and such

the real issue I see with this is for more complicated recipes... because the way this would have to work is we'd need to be able to give the user a better idea of what the possible prices are going to look like... so I think we should aim for this (initially) to be bgMAX

MAX tells how many you can make before break even point, if ah is cheaper then 0, if ah is more expensive then it tells you the cut off based on current prices

-we do some buffering (cut off the absolute cheapest 5%, assume either it's gotten cheaper in which case cool, user saves gold, or it's more expensive, in which case we've hedged our bets)
-do some averaging; add a buffer on number needed and then take averages of each group
-add a buffer on the price target; say ah*.8 or something, such that mats must be a measurable amount cheaper than ah buy price for the target item otherwise this tool recommends that you look at bg+ and compare current prices


Does this make sense... it's 1am and I just came back from tango... so my heads a bit weird

**Comment by unlockedSound** [comment]
closing out, not realistically valuable or viable as described primarily due to the up to two hours of data delay
