### ISSUE TITLE
Test/Prod environment set up and design 

### ISSUE THREAD

**Issue by unlockedSound** [Heanthor/auctioneer-bot#70]
Look into best means to handle test/prod environment set up/architecture/etc.

Will conclude in presenting options followed by selection of one and scoping it.

#69 already captures some of the core concerns, this issue should act as basis for findings and discussion of research.

**Comment by Heanthor** [comment]
Conclusions here:
* Item data will be managed by migration. Add sqitch or flyway to the project, and modify bnet scraper to write to .sql files instead of directly to postgres.
* We are not allowed to publicly share data obtained via Blizzard's API cc 2.N. of https://www.blizzard.com/en-us/legal/a2989b50-5f16-43b1-abec-2ae17cc09dd6/blizzard-developer-api-terms-of-use .
* Any automated step that runs migrations must first download them from the secure s3 bucket where they will be stored. Migrations will not be added to this repo on github.
   * This process should be managed by a bash script that is usable anywhere the bot is run, and is called by the Makefile.
   * The script should first check if new migrations are needed, then check s3 if they exist, and only download them if so.
   * AWS credentials will have to be provided via secret keys to CI/CD pipelines, and managed locally.
* Add information to github README.md which explains why migrations are missing, and provides instructions to generate them yourself (the scraper code is still public).
* Add a privacy policy somewhere cc 2.O. of above.

With the above done, a fresh database can be created and hosted somewhere to be used for testing and local development. Additionally integration tests and CI/CD can rely on this process to run real tests against real data.
