### ISSUE TITLE
!realm Twisting Nether EU command (two names server problem)

### ISSUE THREAD

**Issue by kucukprens** [Heanthor/auctioneer-bot#82]
Hey guys, our server has two names: Twisting Nether EU. I could not do this command :/

what should I do? screenshot: https://i.ibb.co/6YqqR00/twisting-nether-eu.jpg

thanks

**Comment by Heanthor** [comment]
Hey @kucukprens , thanks for filing an issue!

I was able to set the realm with this command:
![image](https://user-images.githubusercontent.com/7563124/89716375-6b709800-d97a-11ea-9b6c-e010919a699a.png)

but I definitely think the error messages you experienced are bad/confusing. There's also some bugs in realm selection that haven't been ironed out since Blizzard updated their API. I'll try to improve this part of the process soon, and test more!

LMK if you can set your realm with this.

**Comment by Heanthor** [comment]
Hmm, but I see other issues with this realm after setting it. I will investigate this some more

**Comment by Heanthor** [comment]
@kucukprens I pushed an update, let me know if the bot works for you now.
